name: Continuous Integration
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build
      run: dotnet build src/WeDev.Extensions.Threading.sln
    - name: Run unit tests
      run: dotnet test --no-build src/WeDev.Extensions.Threading.sln
